# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crawlingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=20)),
                ('viewCount', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=14)),
            ],
        ),
    ]
