# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNU_MOA', '0002_auto_20180929_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingdata',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
