# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNU_MOA', '0003_crawlingdata_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingdata',
            name='date',
        ),
        migrations.AddField(
            model_name='crawlingdata',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crawlingdata',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crawlingdata',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
